---
name: Release Images

on:
  push:
    branches:
      - release-0.15.2


permissions: {}

jobs:
  release:
    name: Release Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0
          platforms: arm64
      - name: Build  lighthouse-inspur
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          platforms: arm64
        run: |
          go mod tidy
          git diff --exit-code
          make images


      - name: Login to Docker
        run: |
          docker login -u inspurwyd  -p  dckr_pat_yMRt21vCZj0PlDl14xJiqSOHeVg

      - name: Push
        run: |
          docker tag  quay.io/submariner/lighthouse-agent:release-0.15  inspurwyd/lighthouse-agent:release-0.15.2-arm64
          docker push  inspurwyd/lighthouse-agent:release-0.15.2-arm64
