---
name: Release Images

on:
  push:
    branches:
      - release-0.15.2

permissions: {}

jobs:
  release:
    name: Release Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Build and release new images
        uses: wangyd1988/shipyard/gh-actions/release-images@v0.15.4
        with:
          username: zhugejingcheng
          password: 1qaz@WSX